            - name: Setup Container Registry
  # You may pin to the exact commit or the version.
  # uses: Sgitario/setup-container-registry@511261d529da1011a9c16ee440af6aa2c665c0ba
  uses: Sgitario/setup-container-registry@v1
  with:
    # The host of the container registry that will be launched
    host: # optional, default is container-registry.org
    # The port of the container registry that will be launched
    port: # optional, default is 5000
          
